// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJadwal() {
  return window['go']['main']['App']['GetJadwal']();
}

export function HapusJadwal(arg1) {
  return window['go']['main']['App']['HapusJadwal'](arg1);
}

export function TambahJadwal(arg1, arg2, arg3) {
  return window['go']['main']['App']['TambahJadwal'](arg1, arg2, arg3);
}

export function ToggleSelesai(arg1) {
  return window['go']['main']['App']['ToggleSelesai'](arg1);
}
