// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetJadwal():Promise<Array<main.JadwalServis>>;

export function HapusJadwal(arg1:number):Promise<Array<main.JadwalServis>>;

export function TambahJadwal(arg1:string,arg2:string,arg3:string):Promise<Array<main.JadwalServis>>;

export function ToggleSelesai(arg1:number):Promise<Array<main.JadwalServis>>;
